# Macro file for example B1
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
#
/control/verbose 2
/run/verbose 2
/event/verbose 0
#/tracking/verbose 2
# 
# gamma 6 MeV to the direction (0.,0.,1.)
#
/gps/particle proton
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/centre 0 0 -10 cm
/gps/pos/radius 2 cm
/gps/ang/type planar
/gps/direction 0 0 1
/gps/ene/mono 13 MeV
#
/run/beamOn 10000000