# Macro file for example B1
# 
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac
#
# Change the default number of workers (in multi-threading mode) 
#/run/numberOfThreads 4
#
# Initialize kernel
/run/initialize
/control/cout/ignoreThreadsExcept 0
#
/control/verbose 2
/run/verbose 1
#
/det/setTargetMaterial  G4_Ta
/det/range 0.04 cm
/analysis/setFileName pTa13MeV
/analysis/h1/set 0 200 0. 15. MeV #Edep(MeV) in first Layer
/analysis/h1/set 1 200 0. 15. MeV #Edep(MeV) in V Layer
/analysis/h1/set 2 200 0. 15. MeV #Edep(MeV) in the target
/analysis/h1/set 3 200 0. 1.4 mm  #projectile range
/gps/particle proton
/gps/pos/type Plane
/gps/pos/shape Circle
/gps/pos/centre 0 0 -10 cm
/gps/pos/radius 2 cm
/gps/ang/type planar
/gps/direction 0 0 1
/gps/ene/mono 13 MeV
/run/beamOn 10000

/det/setTargetMaterial  G4_Fe
/det/range 0.04 cm
/analysis/setFileName pFe13MeV
/run/beamOn 10000